package no.basis.felles.semanticweb.chess.impl;

import no.basis.felles.semanticweb.chess.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTeam <br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */
public class DefaultTeam extends WrappedIndividualImpl implements Team {

    public DefaultTeam(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#owns
     */
     
    public Collection<? extends Player> getOwns() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_OWNS,
                                               DefaultPlayer.class);
    }

    public boolean hasOwns() {
	   return !getOwns().isEmpty();
    }

    public void addOwns(Player newOwns) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_OWNS,
                                       newOwns);
    }

    public void removeOwns(Player oldOwns) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_OWNS,
                                          oldOwns);
    }


    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#plays
     */
     
    public Collection<? extends ChessGame> getPlays() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PLAYS,
                                               DefaultChessGame.class);
    }

    public boolean hasPlays() {
	   return !getPlays().isEmpty();
    }

    public void addPlays(ChessGame newPlays) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PLAYS,
                                       newPlays);
    }

    public void removePlays(ChessGame oldPlays) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PLAYS,
                                          oldPlays);
    }


}
