package no.basis.felles.semanticweb.chess.impl;

import no.basis.felles.semanticweb.chess.*;

import java.net.URI;
import java.util.Collection;

import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultWhiteBoardPosition <br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */
public class DefaultWhiteBoardPosition extends WrappedIndividualImpl implements WhiteBoardPosition {

    public DefaultWhiteBoardPosition(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy
     */
     
    public Collection<? extends Piece> getIsOccupiedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISOCCUPIEDBY,
                                               DefaultPiece.class);
    }

    public boolean hasIsOccupiedBy() {
	   return !getIsOccupiedBy().isEmpty();
    }

    public void addIsOccupiedBy(Piece newIsOccupiedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISOCCUPIEDBY,
                                       newIsOccupiedBy);
    }

    public void removeIsOccupiedBy(Piece oldIsOccupiedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISOCCUPIEDBY,
                                          oldIsOccupiedBy);
    }





	@Override
	public Collection<? extends Chess> getIsPartOf() {
		// TODO Auto-generated method stub
		return null;
	}





	@Override
	public boolean hasIsPartOf() {
		// TODO Auto-generated method stub
		return false;
	}





	@Override
	public void addIsPartOf(Chess newIsPartOf) {
		// TODO Auto-generated method stub
		
	}





	@Override
	public void removeIsPartOf(Chess oldIsPartOf) {
		// TODO Auto-generated method stub
		
	}





	@Override
	public Collection<? extends ChessGame> getPlays() {
		// TODO Auto-generated method stub
		return null;
	}





	@Override
	public boolean hasPlays() {
		// TODO Auto-generated method stub
		return false;
	}





	@Override
	public void addPlays(ChessGame newPlays) {
		// TODO Auto-generated method stub
		
	}





	@Override
	public void removePlays(ChessGame oldPlays) {
		// TODO Auto-generated method stub
		
	}


}
