package no.basis.felles.semanticweb.chess;



import java.util.Collection;

import no.basis.felles.semanticweb.chess.impl.*;
import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.
 *   
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ChessFactory<br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */
public class ChessFactory implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public ChessFactory(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public ChessFactory(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
    public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public Class<?> getJavaInterfaceFromOwlClass(OWLClass cls) {
        return javaMapping.getJavaInterfaceFromOwlClass(cls);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition", BlackBoardPosition.class, DefaultBlackBoardPosition.class);
    }

    /**
     * Creates an instance of type BlackBoardPosition.  Modifies the underlying ontology.
     */
    public BlackBoardPosition createBlackBoardPosition(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_BLACKBOARDPOSITION, DefaultBlackBoardPosition.class);
    }

    /**
     * Gets an instance of type BlackBoardPosition with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public BlackBoardPosition getBlackBoardPosition(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_BLACKBOARDPOSITION, DefaultBlackBoardPosition.class);
    }

    /**
     * Gets all instances of BlackBoardPosition from the ontology.
     */
    public Collection<? extends BlackBoardPosition> getAllBlackBoardPositionInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_BLACKBOARDPOSITION, DefaultBlackBoardPosition.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackPiece
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#BlackPiece", BlackPiece.class, DefaultBlackPiece.class);
    }

    /**
     * Creates an instance of type BlackPiece.  Modifies the underlying ontology.
     */
    public BlackPiece createBlackPiece(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_BLACKPIECE, DefaultBlackPiece.class);
    }

    /**
     * Gets an instance of type BlackPiece with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public BlackPiece getBlackPiece(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_BLACKPIECE, DefaultBlackPiece.class);
    }

    /**
     * Gets all instances of BlackPiece from the ontology.
     */
    public Collection<? extends BlackPiece> getAllBlackPieceInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_BLACKPIECE, DefaultBlackPiece.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BoardPosition
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#BoardPosition", BoardPosition.class, DefaultBoardPosition.class);
    }

    /**
     * Creates an instance of type BoardPosition.  Modifies the underlying ontology.
     */
    public BoardPosition createBoardPosition(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_BOARDPOSITION, DefaultBoardPosition.class);
    }

    /**
     * Gets an instance of type BoardPosition with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public BoardPosition getBoardPosition(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_BOARDPOSITION, DefaultBoardPosition.class);
    }

    /**
     * Gets all instances of BoardPosition from the ontology.
     */
    public Collection<? extends BoardPosition> getAllBoardPositionInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_BOARDPOSITION, DefaultBoardPosition.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chess
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#Chess", Chess.class, DefaultChess.class);
    }

    /**
     * Creates an instance of type Chess.  Modifies the underlying ontology.
     */
    public Chess createChess(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_CHESS, DefaultChess.class);
    }

    /**
     * Gets an instance of type Chess with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Chess getChess(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_CHESS, DefaultChess.class);
    }

    /**
     * Gets all instances of Chess from the ontology.
     */
    public Collection<? extends Chess> getAllChessInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_CHESS, DefaultChess.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#ChessGame
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#ChessGame", ChessGame.class, DefaultChessGame.class);
    }

    /**
     * Creates an instance of type ChessGame.  Modifies the underlying ontology.
     */
    public ChessGame createChessGame(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_CHESSGAME, DefaultChessGame.class);
    }

    /**
     * Gets an instance of type ChessGame with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public ChessGame getChessGame(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_CHESSGAME, DefaultChessGame.class);
    }

    /**
     * Gets all instances of ChessGame from the ontology.
     */
    public Collection<? extends ChessGame> getAllChessGameInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_CHESSGAME, DefaultChessGame.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chessboard
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#Chessboard", Chessboard.class, DefaultChessboard.class);
    }

    /**
     * Creates an instance of type Chessboard.  Modifies the underlying ontology.
     */
    public Chessboard createChessboard(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_CHESSBOARD, DefaultChessboard.class);
    }

    /**
     * Gets an instance of type Chessboard with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Chessboard getChessboard(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_CHESSBOARD, DefaultChessboard.class);
    }

    /**
     * Gets all instances of Chessboard from the ontology.
     */
    public Collection<? extends Chessboard> getAllChessboardInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_CHESSBOARD, DefaultChessboard.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Piece
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#Piece", Piece.class, DefaultPiece.class);
    }

    /**
     * Creates an instance of type Piece.  Modifies the underlying ontology.
     */
    public Piece createPiece(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PIECE, DefaultPiece.class);
    }

    /**
     * Gets an instance of type Piece with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Piece getPiece(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PIECE, DefaultPiece.class);
    }

    /**
     * Gets all instances of Piece from the ontology.
     */
    public Collection<? extends Piece> getAllPieceInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PIECE, DefaultPiece.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceMove
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#PieceMove", PieceMove.class, DefaultPieceMove.class);
    }

    /**
     * Creates an instance of type PieceMove.  Modifies the underlying ontology.
     */
    public PieceMove createPieceMove(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PIECEMOVE, DefaultPieceMove.class);
    }

    /**
     * Gets an instance of type PieceMove with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public PieceMove getPieceMove(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PIECEMOVE, DefaultPieceMove.class);
    }

    /**
     * Gets all instances of PieceMove from the ontology.
     */
    public Collection<? extends PieceMove> getAllPieceMoveInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PIECEMOVE, DefaultPieceMove.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceName
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#PieceName", PieceName.class, DefaultPieceName.class);
    }

    /**
     * Creates an instance of type PieceName.  Modifies the underlying ontology.
     */
    public PieceName createPieceName(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PIECENAME, DefaultPieceName.class);
    }

    /**
     * Gets an instance of type PieceName with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public PieceName getPieceName(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PIECENAME, DefaultPieceName.class);
    }

    /**
     * Gets all instances of PieceName from the ontology.
     */
    public Collection<? extends PieceName> getAllPieceNameInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PIECENAME, DefaultPieceName.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceValue
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#PieceValue", PieceValue.class, DefaultPieceValue.class);
    }

    /**
     * Creates an instance of type PieceValue.  Modifies the underlying ontology.
     */
    public PieceValue createPieceValue(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PIECEVALUE, DefaultPieceValue.class);
    }

    /**
     * Gets an instance of type PieceValue with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public PieceValue getPieceValue(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PIECEVALUE, DefaultPieceValue.class);
    }

    /**
     * Gets all instances of PieceValue from the ontology.
     */
    public Collection<? extends PieceValue> getAllPieceValueInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PIECEVALUE, DefaultPieceValue.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Player
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#Player", Player.class, DefaultPlayer.class);
    }

    /**
     * Creates an instance of type Player.  Modifies the underlying ontology.
     */
    public Player createPlayer(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PLAYER, DefaultPlayer.class);
    }

    /**
     * Gets an instance of type Player with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Player getPlayer(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PLAYER, DefaultPlayer.class);
    }

    /**
     * Gets all instances of Player from the ontology.
     */
    public Collection<? extends Player> getAllPlayerInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PLAYER, DefaultPlayer.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Team
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#Team", Team.class, DefaultTeam.class);
    }

    /**
     * Creates an instance of type Team.  Modifies the underlying ontology.
     */
    public Team createTeam(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_TEAM, DefaultTeam.class);
    }

    /**
     * Gets an instance of type Team with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Team getTeam(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_TEAM, DefaultTeam.class);
    }

    /**
     * Gets all instances of Team from the ontology.
     */
    public Collection<? extends Team> getAllTeamInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_TEAM, DefaultTeam.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition", WhiteBoardPosition.class, DefaultWhiteBoardPosition.class);
    }

    /**
     * Creates an instance of type WhiteBoardPosition.  Modifies the underlying ontology.
     */
    public WhiteBoardPosition createWhiteBoardPosition(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_WHITEBOARDPOSITION, DefaultWhiteBoardPosition.class);
    }

    /**
     * Gets an instance of type WhiteBoardPosition with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public WhiteBoardPosition getWhiteBoardPosition(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_WHITEBOARDPOSITION, DefaultWhiteBoardPosition.class);
    }

    /**
     * Gets all instances of WhiteBoardPosition from the ontology.
     */
    public Collection<? extends WhiteBoardPosition> getAllWhiteBoardPositionInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_WHITEBOARDPOSITION, DefaultWhiteBoardPosition.class);
    }


    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhitePiece
     */

    {
        javaMapping.add("http://www.co-ode.org/ontologies/ont.owl#WhitePiece", WhitePiece.class, DefaultWhitePiece.class);
    }

    /**
     * Creates an instance of type WhitePiece.  Modifies the underlying ontology.
     */
    public WhitePiece createWhitePiece(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_WHITEPIECE, DefaultWhitePiece.class);
    }

    /**
     * Gets an instance of type WhitePiece with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public WhitePiece getWhitePiece(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_WHITEPIECE, DefaultWhitePiece.class);
    }

    /**
     * Gets all instances of WhitePiece from the ontology.
     */
    public Collection<? extends WhitePiece> getAllWhitePieceInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_WHITEPIECE, DefaultWhitePiece.class);
    }


}
