package no.basis.felles.semanticweb.chess;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PieceName <br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */

public interface PieceName extends Piece, Chess {

    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#isPartOf
     */
     
    /**
     * Gets all property values for the isPartOf property.<p>
     * 
     * @returns a collection of values for the isPartOf property.
     */
    Collection<? extends Chess> getIsPartOf();

    /**
     * Checks if the class has a isPartOf property value.<p>
     * 
     * @return true if there is a isPartOf property value.
     */
    boolean hasIsPartOf();

    /**
     * Adds a isPartOf property value.<p>
     * 
     * @param newIsPartOf the isPartOf property value to be added
     */
    void addIsPartOf(Chess newIsPartOf);

    /**
     * Removes a isPartOf property value.<p>
     * 
     * @param oldIsPartOf the isPartOf property value to be removed.
     */
    void removeIsPartOf(Chess oldIsPartOf);


    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#occupies
     */
     
    /**
     * Gets all property values for the occupies property.<p>
     * 
     * @returns a collection of values for the occupies property.
     */
    Collection<? extends BoardPosition> getOccupies();

    /**
     * Checks if the class has a occupies property value.<p>
     * 
     * @return true if there is a occupies property value.
     */
    boolean hasOccupies();

    /**
     * Adds a occupies property value.<p>
     * 
     * @param newOccupies the occupies property value to be added
     */
    void addOccupies(BoardPosition newOccupies);

    /**
     * Removes a occupies property value.<p>
     * 
     * @param oldOccupies the occupies property value to be removed.
     */
    void removeOccupies(BoardPosition oldOccupies);


    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#hasName
     */
     
    /**
     * Gets all property values for the hasName property.<p>
     * 
     * @returns a collection of values for the hasName property.
     */
    Collection<? extends String> getHasName();

    /**
     * Checks if the class has a hasName property value.<p>
     * 
     * @return true if there is a hasName property value.
     */
    boolean hasHasName();

    /**
     * Adds a hasName property value.<p>
     * 
     * @param newHasName the hasName property value to be added
     */
    void addHasName(String newHasName);

    /**
     * Removes a hasName property value.<p>
     * 
     * @param oldHasName the hasName property value to be removed.
     */
    void removeHasName(String oldHasName);



    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#hasValue
     */
     
    /**
     * Gets all property values for the hasValue property.<p>
     * 
     * @returns a collection of values for the hasValue property.
     */
    Collection<? extends Integer> getHasValue();

    /**
     * Checks if the class has a hasValue property value.<p>
     * 
     * @return true if there is a hasValue property value.
     */
    boolean hasHasValue();

    /**
     * Adds a hasValue property value.<p>
     * 
     * @param newHasValue the hasValue property value to be added
     */
    void addHasValue(Integer newHasValue);

    /**
     * Removes a hasValue property value.<p>
     * 
     * @param oldHasValue the hasValue property value to be removed.
     */
    void removeHasValue(Integer oldHasValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
