package no.basis.felles.semanticweb.chess;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Player <br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */

public interface Player extends Chess {

    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#plays
     */
     
    /**
     * Gets all property values for the plays property.<p>
     * 
     * @returns a collection of values for the plays property.
     */
    Collection<? extends ChessGame> getPlays();

    /**
     * Checks if the class has a plays property value.<p>
     * 
     * @return true if there is a plays property value.
     */
    boolean hasPlays();

    /**
     * Adds a plays property value.<p>
     * 
     * @param newPlays the plays property value to be added
     */
    void addPlays(ChessGame newPlays);

    /**
     * Removes a plays property value.<p>
     * 
     * @param oldPlays the plays property value to be removed.
     */
    void removePlays(ChessGame oldPlays);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
