package no.basis.felles.semanticweb.chess;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Aug 04 14:11:10 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackPiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackPiece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chess
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESS.<p>
     * 
     */
    public static final OWLClass CLASS_CHESS = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Chess"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#ChessGame
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSGAME.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSGAME = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#ChessGame"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chessboard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSBOARD.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSBOARD = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Chessboard"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Piece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECE.<p>
     * 
     */
    public static final OWLClass CLASS_PIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Piece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceMove
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECEMOVE.<p>
     * 
     */
    public static final OWLClass CLASS_PIECEMOVE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#PieceMove"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceName
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECENAME.<p>
     * 
     */
    public static final OWLClass CLASS_PIECENAME = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#PieceName"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#PieceValue
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECEVALUE.<p>
     * 
     */
    public static final OWLClass CLASS_PIECEVALUE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#PieceValue"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Player
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_PLAYER = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Player"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Team
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEAM.<p>
     * 
     */
    public static final OWLClass CLASS_TEAM = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Team"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhitePiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhitePiece"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOCCUPIEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOCCUPIEDBY = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isPartOf"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#occupies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OCCUPIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OCCUPIES = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#occupies"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#owns
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWNS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWNS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#owns"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#plays
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLAYS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLAYS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#plays"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasName"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasValue"));


}
