package no.basis.felles.semanticweb.chess;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: WhiteBoardPosition <br>
 * @version generated on Fri Aug 04 14:11:11 CEST 2017 by oluf
 * @deprecated as of August 2018. Replaced by Project chessontology
 */

public interface WhiteBoardPosition extends BoardPosition {

    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy
     */
     
    /**
     * Gets all property values for the isOccupiedBy property.<p>
     * 
     * @returns a collection of values for the isOccupiedBy property.
     */
    Collection<? extends Piece> getIsOccupiedBy();

    /**
     * Checks if the class has a isOccupiedBy property value.<p>
     * 
     * @return true if there is a isOccupiedBy property value.
     */
    boolean hasIsOccupiedBy();

    /**
     * Adds a isOccupiedBy property value.<p>
     * 
     * @param newIsOccupiedBy the isOccupiedBy property value to be added
     */
    void addIsOccupiedBy(Piece newIsOccupiedBy);

    /**
     * Removes a isOccupiedBy property value.<p>
     * 
     * @param oldIsOccupiedBy the isOccupiedBy property value to be removed.
     */
    void removeIsOccupiedBy(Piece oldIsOccupiedBy);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
